flags: {}
extra-package-dbs: []
packages:
- '.'
setup-info:
  ghc:
    linux64:
      8.0.0.20160411:
        url: https://downloads.haskell.org/~ghc/8.0.1-rc4/ghc-8.0.0.20160421-x86_64-deb8-linux.tar.xz
        sha1: 6e8bd7c96fa46da0b8c12bf9d62f006940adfe67
extra-deps:
- QuickCheck-2.8.2
- compdata-0.10
- cpphs-1.20.1
- derive-2.5.24
- hashable-1.2.4.0
- haskell-src-exts-1.17.1
- ho-rewriting-0.2
- mtl-2.2.1
- old-locale-1.0.0.7
- old-time-1.1.0.3
- patch-combinators-0.2.2
- polyparse-1.12
- primitive-0.6.1.0
- random-1.1
- syb-0.6
- text-1.2.2.1
- tf-random-0.5
- th-expand-syns-0.4.0.0
- tree-view-0.4
- uniplate-1.6.12
- unordered-containers-0.2.7.0
# compiler: lts-5.3
#ghc-8.0.0.20160411
resolver: lts-5.3
# ghc-8.0.0.20160411
nix:
    enable: true
    packages: [ pkgs.haskellPackages.ghcid pkgs.haskellPackages.happy ]


